# Generated by Django 5.1.1 on 2024-10-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_orangtua', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('alamat', models.TextField(blank=True)),
                ('nomor_hp', models.CharField(max_length=15)),
            ],
        ),
    ]
