# Generated by Django 5.1.1 on 2024-10-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transaksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaksi.transaksi')),
            ],
        ),
    ]
