# Generated by Django 5.1.1 on 2024-10-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=10)),
                ('nomor_orangtua', models.CharField(max_length=15)),
            ],
        ),
    ]
