# Generated by Django 5.1.1 on 2024-10-23 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaksi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='jenis_transaksi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kategori_pemasukan',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kategori_pengeluaran',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='deskripsi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaksi',
            name='kategori',
            field=models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
