# Generated by Django 5.1.1 on 2024-10-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaksi', '0002_remove_transaksi_jenis_transaksi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='kategori',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('PEMASUKAN', 'Pemasukan'), ('PENGELUARAN', 'Pengeluaran')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='kategori_pemasukan',
            field=models.CharField(blank=True, choices=[('SPP', 'Pembayaran SPP'), ('UANG_PANGKAL', 'Pembayaran Uang Pangkal'), ('HIBAH', 'Hibah'), ('LAINNYA', 'Pemasukan Lainnya')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='kategori_pengeluaran',
            field=models.CharField(blank=True, choices=[('OPERASIONAL', 'Biaya Operasional'), ('ADMINISTRASI', 'Biaya Administrasi'), ('GAJI_KARYAWAN', 'Gaji Karyawan'), ('LAINNYA', 'Pengeluaran Lainnya')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
