# Generated by Django 5.1.1 on 2024-10-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengingat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Siswa.siswa')),
            ],
        ),
    ]
